// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSUY-jTb39_YVYTRLmkybly8j-Nc66TtA',
    appId: '1:199964689795:web:6681c6512cc282501162b6',
    messagingSenderId: '199964689795',
    projectId: 'rallychamp',
    authDomain: 'rallychamp.firebaseapp.com',
    storageBucket: 'rallychamp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgzK4svjb5BWnwdUv-230oLrKbvH7yJME',
    appId: '1:199964689795:android:835d3743d59cfbc41162b6',
    messagingSenderId: '199964689795',
    projectId: 'rallychamp',
    storageBucket: 'rallychamp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi-IWAbMaGMgagZ4MAz0_DsW8Gvc4L_m4',
    appId: '1:199964689795:ios:4d30518da29ce3a21162b6',
    messagingSenderId: '199964689795',
    projectId: 'rallychamp',
    storageBucket: 'rallychamp.firebasestorage.app',
    iosBundleId: 'com.example.rallychamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi-IWAbMaGMgagZ4MAz0_DsW8Gvc4L_m4',
    appId: '1:199964689795:ios:4d30518da29ce3a21162b6',
    messagingSenderId: '199964689795',
    projectId: 'rallychamp',
    storageBucket: 'rallychamp.firebasestorage.app',
    iosBundleId: 'com.example.rallychamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSUY-jTb39_YVYTRLmkybly8j-Nc66TtA',
    appId: '1:199964689795:web:350f483e7ed5ab101162b6',
    messagingSenderId: '199964689795',
    projectId: 'rallychamp',
    authDomain: 'rallychamp.firebaseapp.com',
    storageBucket: 'rallychamp.firebasestorage.app',
  );
}
